## 프라미스

1. promise는 resolve또는 reject를 호출해서 그 결과를 반환한다.
2. 마치 return하는 것처럼, 반드시 하나는 호출해야 한다. 호출하지 않으면 pending상태 지속
3. finally는 가장 마지막에 오지 않아도 된다.
4. finally는 인수가 없다.

```
new Promise((resolve,reject)=>{resolve('hello world!')}).finally(()=>{}).then(alert)
```

5. 위 예시의 경우처럼 finally의 인수는 없다. finally(함수)로 전달하면 그대로 수행된다.
6. then(f1,f2)가 가능한데, resolve인 경우 f1, reject인 경우 f2가 호출된다.

```
new Promise((resolve,reject)=>{resolve('hello world!')}).finally().then((x)=>{alert(x)})
```

7. 위 예시의 경우 'hello world!'가 alert로 출력된다. 프라미스 결과가 finally를 통해 전달 된 것
8. 프로미스안에 resolve 또는 reject가 다수 있더라도 가장 위에 있는 resolve또는 reject가 호출되어 반환된다. 반환된 후에는 (비동기적으로) 그 이후에 있는 (resolve/reject가 아닌) 코드도 실행된다.
9. 프라미스 체이닝은 프라미스.then().then()...then() 형식이 될 수는 있지만, `then 또한 프라미스를 return`해야 한다.

```
new Promise((resolve,reject)=>{resolve(1)}).then((result)=>return result).then(()=>{})...
```

10. 하나의 프라미스는 하나의 핸들러를 등록해서 사용한다(=동일한 프라미스에 여러개의 핸들러(then)를 각각 등록하더라도 같은 결과)
11. 프라미스를 생성할 때, 프라미스가 처리될 때 까지 기다린 뒤 그 결과를 받는다.(안에 비동기 함수(예: setTimeout)이 중첩되어있더라도 모두 기다린 후 resolve 또는 reject를 호출하여 그 값을 프라미스 객체를 통해 반환하고 그 결과가 then으로 전달된다.)

```
function nestedCallbacks() {
  return new Promise((resolve) => {
    setTimeout(() => {
      setTimeout(() => {
        setTimeout(() => {
          setTimeout(() => {
            setTimeout(() => {
              resolve("hello");
            }, 1000);
          }, 1000);
        }, 1000);
      }, 1000);
    }, 1000);
  });
}
nestedCallbacks().then(result=>alert(result))

```

12. .then((result)=>result) 라면, result는 프라미스가 아니라, 다음 then 메서드로 값이 전달되는 것
13. 프라미스에 연결된 then이 여러개라도, 하나의 then에서 오류가 발생한다면 뒤의 then을 건너뛰고 catch로 간다.

### 프라미스와 에러 핸들링

`암시적 try...catch`

- `동기적` 에러는 암시적 try...catch에서 처리된다. 즉,

```
new Promise((resolve,reject)=>{
    setTimeout(()=>{
        reject('error')
    },1000)
}).catch(alert) //catch에서 처리

new Promise((resolve,reject)=>{
    setTimeout(()=>{
        throw new Error('error')//암시적 try...catch
    },1000)
}).catch(alert)
```

### 프라미스 API

정적 메서드는 new 없이 Promise.메서드로 호출한다.

#### Promise.all

```
//모두 resolve
Promise.all([new Promise(resolve => setTimeout(()=>resolve(3),1000)),new Promise(resolve => setTimeout(()=>resolve(2),2000)),new Promise(resolve => setTimeout(()=>resolve(1),3000))]).then(alert)

//reject가 있는 경우
Promise.all([new Promise(resolve => setTimeout(()=>resolve(3),1000)),new Promise(resolve => setTimeout(()=>resolve(2),2000)),new Promise(resolve => setTimeout(()=>resolve(1),3000))]).then(alert)

Promise.all([new Promise(resolve => setTimeout(()=>resolve(3),1000)),new Promise((resolve ,reject)=> setTimeout(()=>reject(2),2000)),new Promise(resolve => setTimeout(()=>resolve(1),3000),new Promise(resolve=>{setTimeout(()=>console.log('호출여부 확인'),5000); setTimeout(()=>resolve('4'),4000)}))]).then(alert).catch(alert)
```

1. 배열(이터러블) 안의 모든 프라미스가 처리(resolve)되면 처리된 순서(위에는 timeout 순서)대로 결괏값이 담긴다.
2. 만약 하나라도 거부된다면 즉시 Promise.all이 거부되고 catch가 실행된다. 그 이후에 처리되는 프라미스가 전부 거부된다.
3. Promise.all은 거부되지만, 호출은 계속 일어난다. 프라미스의 처리만 무시된다 = 프라미스는 취소가 없다
4. 프라미스가 아닌 일반 값도 배열에 전달된다.

